# Generated by Django 4.2.22 on 2025-06-04 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeproposal',
            options={'verbose_name': 'Обмен', 'verbose_name_plural': 'Обмены'},
        ),
        migrations.AlterModelTable(
            name='exchangeproposal',
            table='Trades',
        ),
    ]
